/**
 * AIWG.md and AGENTS.md generator.
 *
 * Per ADR-1: this module assembles the two project-root context files at the end of
 * `aiwg use`. AIWG.md is CLAUDE.md-shaped framework context for non-Claude providers;
 * AGENTS.md is a link-indexed bridge that points to AIWG.md and to deployed artifact
 * files. See `.aiwg/architecture/adr-agents-md-aggregation.md` for the full spec.
 *
 * This file contains the public generator API. Callers are expected to have already
 * deployed artifacts and to pass pre-aggregated `AgentsMdSection[]` describing what
 * was deployed. The generator does not walk the filesystem to discover artifacts;
 * that's the caller's responsibility (per ADR-1 §7 generator-runs-after-deploy
 * invariant — the caller knows what landed).
 */

import { promises as fs } from 'node:fs';
import * as path from 'node:path';
import type {
  ContextPipelineOptions,
  ContextPipelineResult,
  AgentsMdSection,
  IndexEntry,
  IndexedArtifactType,
} from './types.js';
import { sanitizeDescription, sanitizeTags } from './sanitizer.js';
import { checkPathAllowed } from './allowlist.js';
import { generateAiwgMd } from './aiwg-md.js';

const SECTION_TITLES: Record<IndexedArtifactType, string> = {
  agents: 'Agents',
  rules: 'Rules',
  skills: 'Skills',
  behaviors: 'Behaviors',
};

const AIWG_SIGNATURE_COMMENT = '<!-- aiwg-managed -->';

/**
 * Render a single link-index entry as markdown.
 *
 * Returns null if the entry is rejected by sanitizer or allowlist; the caller can
 * accumulate warnings about dropped entries.
 */
export function renderEntry(entry: IndexEntry): { markdown: string | null; warning: string } {
  const desc = sanitizeDescription(entry.description);
  if (!desc.ok) {
    return {
      markdown: null,
      warning: `dropped entry '${entry.id}': description rejected (${desc.rejectedFor})`,
    };
  }

  const allowed = checkPathAllowed(entry.path);
  if (!allowed.ok) {
    return {
      markdown: null,
      warning: `dropped entry '${entry.id}': path rejected (${allowed.rejectedFor})`,
    };
  }

  let suffix = '';
  if (entry.safetyCritical) {
    suffix = entry.shadowedBy
      ? ` *(SAFETY-CRITICAL, SHADOWED → ${entry.shadowedBy})*`
      : ' *(SAFETY-CRITICAL)*';
  }

  const tagPart = entry.tags && entry.tags.length > 0
    ? `\n  - Tags: ${sanitizeTags(entry.tags).kept.join(', ')}`
    : '';

  const userScopeMarker = allowed.isUserScope
    ? '\n  <!-- user-scope; loader may not auto-resolve -->'
    : '';

  const markdown = `- **${entry.id}**${suffix} — ${desc.value}\n  - Path: \`${entry.path}\`${tagPart}${userScopeMarker}`;

  return { markdown, warning: '' };
}

/**
 * Render one section (e.g. ## Agents) of an AGENTS.md.
 */
export function renderSection(section: AgentsMdSection): { markdown: string; warnings: string[] } {
  const title = SECTION_TITLES[section.type];
  const warnings: string[] = [];
  const lines: string[] = [];

  for (const entry of section.entries) {
    const { markdown, warning } = renderEntry(entry);
    if (markdown) {
      lines.push(markdown);
    } else if (warning) {
      warnings.push(warning);
    }
  }

  if (lines.length === 0) {
    // Empty sections are omitted per ADR-1 §1
    return { markdown: '', warnings };
  }

  return {
    markdown: `## ${title}\n\n${lines.join('\n\n')}\n`,
    warnings,
  };
}

/**
 * Build the full AGENTS.md content (in-memory; does not write).
 */
export function buildAgentsMd(opts: ContextPipelineOptions): { content: string; warnings: string[] } {
  const warnings: string[] = [];
  const parts: string[] = [];

  parts.push('# AGENTS.md');
  parts.push(`${AIWG_SIGNATURE_COMMENT}`);
  parts.push('<!-- Generated by AIWG. Edit AGENTS.override.md for operator additions. -->');
  parts.push('');
  parts.push('## Framework Context');
  parts.push('');
  parts.push('See [AIWG.md](./AIWG.md) for the full AIWG framework context');
  parts.push('(active frameworks, addons, agents, behaviors, rules).');
  parts.push('');

  if (opts.projectContext && opts.projectContext.trim().length > 0) {
    const desc = sanitizeDescription(opts.projectContext.slice(0, 1000));
    if (desc.ok) {
      parts.push('## Project Context');
      parts.push('');
      parts.push(desc.value);
      parts.push('');
    } else {
      warnings.push(`dropped Project Context section: ${desc.rejectedFor}`);
    }
  }

  for (const section of opts.sections) {
    const { markdown, warnings: secWarnings } = renderSection(section);
    if (markdown) {
      parts.push(markdown);
    }
    warnings.push(...secWarnings);
  }

  parts.push('---');
  parts.push('');
  parts.push('*See `AGENTS.override.md` for operator-authored additions and overflow.*');
  parts.push('');

  return { content: parts.join('\n'), warnings };
}

/**
 * Detect whether a pre-existing file at `filePath` carries the AIWG signature.
 *
 * Returns `true` if the file is missing or is AIWG-managed (safe to overwrite).
 * Returns `false` if the file exists and does not carry the signature comment
 * (operator-claimed).
 */
export async function isOverwriteSafe(filePath: string): Promise<boolean> {
  try {
    const content = await fs.readFile(filePath, 'utf8');
    // Look only in the first 4 lines so a stray signature deeper in the file
    // doesn't trick the check.
    const head = content.split('\n').slice(0, 4).join('\n');
    if (head.includes(AIWG_SIGNATURE_COMMENT)) return true;
    // Backwards compatibility: pre-ADR-1 AIWG releases generated AIWG.md
    // with "Generated by aiwg use" or "Generated by AIWG" markers but no
    // signature comment. Treat those as AIWG-managed so existing repos
    // upgrade cleanly without the operator needing --force-context-files.
    if (/Generated by\s+(AIWG|aiwg)/i.test(head)) return true;
    return false;
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === 'ENOENT') {
      return true;
    }
    throw err;
  }
}

/**
 * Atomically write a file via tmpfile + rename.
 *
 * Per ADR-4 §4 atomic write requirement; on failure no partial state is persisted.
 */
async function atomicWrite(filePath: string, content: string): Promise<void> {
  const dir = path.dirname(filePath);
  const tmp = path.join(dir, `.${path.basename(filePath)}.tmp.${process.pid}`);
  await fs.writeFile(tmp, content, 'utf8');
  try {
    await fs.rename(tmp, filePath);
  } catch (err) {
    // Best-effort cleanup of tmpfile on rename failure.
    await fs.unlink(tmp).catch(() => undefined);
    throw err;
  }
}

/**
 * Generate AIWG.md and AGENTS.md at the project root.
 *
 * Skeleton implementation: emits AGENTS.md with link-index sections; AIWG.md
 * generation is wired in commit 3 alongside the first issue closure (#1104).
 * For now AIWG.md emission delegates to a copy of CLAUDE.md when the source
 * is present; otherwise it is skipped with a warning.
 */
export async function generate(opts: ContextPipelineOptions): Promise<ContextPipelineResult> {
  const result: ContextPipelineResult = {
    aiwgMdPath: '',
    agentsMdPath: '',
    twinPaths: [],
    backupPaths: [],
    agentsMdBytes: 0,
    warnings: [],
  };

  if (!opts.skip?.agentsMd) {
    const agentsMdPath = path.join(opts.projectPath, 'AGENTS.md');

    if (opts.detectExistingFiles && !opts.force) {
      const safe = await isOverwriteSafe(agentsMdPath);
      if (!safe) {
        result.warnings.push(
          `AGENTS.md exists and is not AIWG-managed; not overwritten. Pass --force to back up and replace.`,
        );
      } else {
        const { content, warnings } = buildAgentsMd(opts);
        await atomicWrite(agentsMdPath, content);
        result.agentsMdPath = agentsMdPath;
        result.agentsMdBytes = Buffer.byteLength(content, 'utf8');
        result.warnings.push(...warnings);
      }
    } else if (opts.force) {
      // Backup before overwrite per ADR-1 §5 R1 mitigation.
      try {
        const original = await fs.readFile(agentsMdPath, 'utf8');
        if (!original.includes(AIWG_SIGNATURE_COMMENT)) {
          const backupPath = `${agentsMdPath}.bak.${new Date().toISOString().replace(/[:.]/g, '-')}`;
          await fs.writeFile(backupPath, original, 'utf8');
          result.backupPaths.push(backupPath);
        }
      } catch (err) {
        if ((err as NodeJS.ErrnoException).code !== 'ENOENT') {
          throw err;
        }
      }
      const { content, warnings } = buildAgentsMd(opts);
      await atomicWrite(agentsMdPath, content);
      result.agentsMdPath = agentsMdPath;
      result.agentsMdBytes = Buffer.byteLength(content, 'utf8');
      result.warnings.push(...warnings);
    } else {
      const { content, warnings } = buildAgentsMd(opts);
      await atomicWrite(agentsMdPath, content);
      result.agentsMdPath = agentsMdPath;
      result.agentsMdBytes = Buffer.byteLength(content, 'utf8');
      result.warnings.push(...warnings);
    }
  }

  if (!opts.skip?.aiwgMd) {
    const aiwgMdPath = path.join(opts.projectPath, 'AIWG.md');

    let canWrite = true;
    if (opts.detectExistingFiles && !opts.force) {
      canWrite = await isOverwriteSafe(aiwgMdPath);
      if (!canWrite) {
        result.warnings.push(
          'AIWG.md exists and is not AIWG-managed; not overwritten. Pass --force to back up and replace.',
        );
      }
    } else if (opts.force) {
      // Backup before overwrite per ADR-1 §5 R1 mitigation.
      try {
        const original = await fs.readFile(aiwgMdPath, 'utf8');
        if (!original.includes(AIWG_SIGNATURE_COMMENT)) {
          const backupPath = `${aiwgMdPath}.bak.${new Date().toISOString().replace(/[:.]/g, '-')}`;
          await fs.writeFile(backupPath, original, 'utf8');
          result.backupPaths.push(backupPath);
        }
      } catch (err) {
        if ((err as NodeJS.ErrnoException).code !== 'ENOENT') {
          throw err;
        }
      }
    }

    if (canWrite) {
      const content = await generateAiwgMd(opts.projectPath);
      await atomicWrite(aiwgMdPath, content);
      result.aiwgMdPath = aiwgMdPath;
    }
  }

  return result;
}
