// This file is generated by scripts/generate-types.mjs from flow-graph.schema.json.
// Do not edit it directly.

/** Provider-neutral graph profile for the AIWG Flow metalanguage. */
export interface FlowGraph {
  apiVersion: "flow.aiwg.io/v1alpha1";
  kind: "FlowGraph";
  metadata: Metadata;
  spec: Spec;
}

export interface Metadata {
  name: DnsLabel;
  namespace?: DnsLabel;
  labels?: StringMap;
  annotations?: StringMap;
}

export interface Spec {
  description?: string;
  entry: Array<Id>;
  candidates: Array<Candidate>;
  state: State;
  permissions: Array<Permission>;
  capabilities: Array<Capability>;
  ceilings: Ceilings;
  nodes: Array<Node>;
  routes: Array<Route>;
  joins: Array<Join>;
  failure: FailurePolicy;
  output: OutputPolicy;
  trace: TracePolicy;
}

export interface Candidate {
  id: IndexRef;
  kind: ArtifactKind;
  schema?: JsonSchema;
}

export interface State {
  fields: Array<StateField>;
}

export interface StateField {
  name: Id;
  schema: JsonSchema;
  reducer: "replace" | "append" | "merge" | "sum" | "min" | "max" | "set-union";
  initial?: unknown;
}

export interface Capability {
  id: Id;
  permissions: Array<Permission>;
  sideEffectMode: SideEffectMode;
  idempotencyKey?: string;
  approvalGate?: Id;
}

export interface Ceilings {
  activations: number;
  tokens: number;
  costUsd: number;
  timeMs: number;
  concurrency: number;
}

export interface Node {
  id: Id;
  kind: NodeKind;
  ref?: IndexRef;
  deterministic?: true;
  description?: string;
  optional?: boolean;
  phase?: string;
  track?: string;
  dependsOn?: Array<Id>;
  activation?: Predicate;
  inputs: Array<InputBinding>;
  outputs: Array<OutputBinding>;
  capabilities: Array<Id>;
  permissions: Array<Permission>;
  sideEffectMode: SideEffectMode;
  idempotencyKey?: string;
  approvalGate?: Id;
  scope?: ObservationScope;
  retry?: RetryPolicy;
  fallback?: FallbackPolicy;
  ceilings?: Ceilings;
}

export interface InputBinding {
  name: Id;
  schema: JsonSchema;
  from?: string;
  state?: Id;
  value?: unknown;
}

export interface OutputBinding {
  name: Id;
  schema: JsonSchema;
  state?: Id;
}

export interface Route {
  id?: Id;
  from: Id;
  to: Id;
  when?: Predicate;
  guard?: Predicate;
  progress?: ProgressMeasure;
  maxIterations?: number;
}

export interface ProgressMeasure {
  state: Id;
  direction: "decrease";
}

export interface ObservationScope {
  files?: Array<string>;
  resources?: Array<string>;
}

export interface Join {
  id: Id;
  sources: Array<Id>;
  target: Id;
  policy: {
  mode: "all" | "quorum" | "fixed" | "lcm" | "converged" | "budget";
  quorum?: number;
  count?: number;
  periods?: Array<number>;
  predicate?: Predicate;
  maxIterations?: number;
  maxCostUsd?: number;
};
}

export interface FailurePolicy {
  onNodeFailure: "fail" | "continue" | "skip-optional" | "fallback" | "partial-synthesis";
  maxFailures: number;
  terminalSchema?: JsonSchema;
}

export interface OutputPolicy {
  mode: "final-only" | "progressive" | "typed-terminal-failure";
  from: string;
  schema: JsonSchema;
  failureSchema?: JsonSchema;
}

export interface TracePolicy {
  level: "metadata" | "bindings" | "full-io";
  redact: Array<string>;
}

export interface RetryPolicy {
  limit: number;
  backoff: "none" | "linear" | "exponential";
  on: Array<"failure" | "timeout" | "rate-limit">;
}

export interface FallbackPolicy {
  node: Id;
  allowPartial?: boolean;
}

export interface Predicate {
  language?: "cel";
  expression: string;
}

export interface JsonSchema {
  [key: string]: unknown;
}

export type NodeKind = "agent" | "skill" | "prompt" | "evaluator" | "tool" | "function" | "gate";

export type ArtifactKind = "agent" | "skill" | "prompt" | "evaluator" | "tool" | "function";

export type SideEffectMode = "none" | "idempotent" | "exactly-once" | "approval-required";

export type Permission = string;

export type IndexRef = string;

export type Id = string;

export type DnsLabel = string;

export interface StringMap {
  [key: string]: string;
}
