import { access, cp, mkdir, readFile, readdir, rename, rm, rmdir, stat, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { buildIndex } from './index-builder.js';
import { syncFortemiCoreIndex } from './fortemi-core-sync.js';
import {
  PROJECT_AIWG_LOCATION_FILE,
  expandProjectArtifactPath,
  resolveProjectAiwgDir,
} from '../config/project-artifacts.js';

export interface MoveProjectArtifactsOptions {
  projectDir: string;
  from?: string;
  to: string;
  dryRun?: boolean;
  force?: boolean;
  reindex?: boolean;
  syncFortemi?: boolean;
}

export interface MoveProjectArtifactsResult {
  projectDir: string;
  from: string;
  to: string;
  pointerPath: string;
  pointerValue: string;
  moved: boolean;
  gitignoreUpdated: boolean;
  reindexed: boolean;
  fortemiSynced: boolean;
  dryRun: boolean;
}

const GITIGNORE_BLOCK = [
  '',
  '# AIWG artifact root pointer (local/private path)',
  PROJECT_AIWG_LOCATION_FILE,
  '',
].join('\n');

async function exists(filePath: string): Promise<boolean> {
  try {
    await access(filePath);
    return true;
  } catch {
    return false;
  }
}

function samePath(left: string, right: string): boolean {
  return path.resolve(left) === path.resolve(right);
}

async function isEmptyDirectory(dir: string): Promise<boolean> {
  try {
    const info = await stat(dir);
    if (!info.isDirectory()) return false;
    const entries = await readdir(dir);
    return entries.length === 0;
  } catch {
    return false;
  }
}

function pointerValueFor(projectDir: string, destination: string): string {
  const relative = path.relative(projectDir, destination).split(path.sep).join('/');
  return relative.length > 0 ? relative : '.';
}

async function ensureGitignorePointer(projectDir: string, dryRun: boolean): Promise<boolean> {
  const gitignorePath = path.join(projectDir, '.gitignore');
  let current = '';
  try {
    current = await readFile(gitignorePath, 'utf-8');
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error;
  }

  const lines = current.split(/\r?\n/).map(line => line.trim());
  if (lines.includes(PROJECT_AIWG_LOCATION_FILE)) return false;
  if (!dryRun) {
    const separator = current.length === 0 || current.endsWith('\n') ? '' : '\n';
    await writeFile(gitignorePath, `${current}${separator}${GITIGNORE_BLOCK}`, 'utf-8');
  }
  return true;
}

async function writePointer(projectDir: string, pointerValue: string, dryRun: boolean): Promise<string> {
  const pointerPath = path.join(projectDir, PROJECT_AIWG_LOCATION_FILE);
  if (!dryRun) {
    await writeFile(
      pointerPath,
      [
        '# AIWG artifact root.',
        '# Generated by `aiwg artifacts move`; AIWG_ARTIFACTS_PATH overrides this file.',
        pointerValue,
        '',
      ].join('\n'),
      'utf-8',
    );
  }
  return pointerPath;
}

async function moveDirectory(source: string, destination: string): Promise<void> {
  const destinationExists = await exists(destination);
  if (destinationExists) {
    if (!(await isEmptyDirectory(destination))) {
      throw new Error(`Destination already exists and is not empty: ${destination}`);
    }
    await rmdir(destination);
  }
  await mkdir(path.dirname(destination), { recursive: true });
  try {
    await rename(source, destination);
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== 'EXDEV') throw error;
    await cp(source, destination, { recursive: true, errorOnExist: true, force: false });
    await rm(source, { recursive: true, force: false });
  }
}

async function withTemporaryArtifactEnv<T>(artifactDir: string, callback: () => Promise<T>): Promise<T> {
  const previous = process.env.AIWG_ARTIFACTS_PATH;
  process.env.AIWG_ARTIFACTS_PATH = artifactDir;
  try {
    return await callback();
  } finally {
    if (previous === undefined) {
      delete process.env.AIWG_ARTIFACTS_PATH;
    } else {
      process.env.AIWG_ARTIFACTS_PATH = previous;
    }
  }
}

export async function moveProjectArtifacts(
  options: MoveProjectArtifactsOptions,
): Promise<MoveProjectArtifactsResult> {
  const projectDir = path.resolve(options.projectDir);
  const source = path.resolve(
    options.from ? expandProjectArtifactPath(options.from, projectDir) : resolveProjectAiwgDir(projectDir),
  );
  const destination = path.resolve(expandProjectArtifactPath(options.to, projectDir));
  const dryRun = options.dryRun === true;
  const reindex = options.reindex !== false;
  const syncFortemi = options.syncFortemi !== false;

  if (samePath(source, destination)) {
    throw new Error(`Source and destination are the same directory: ${source}`);
  }

  if (!existsSync(source)) {
    throw new Error(`Source AIWG artifact directory does not exist: ${source}`);
  }

  if (existsSync(destination) && !(await isEmptyDirectory(destination))) {
    throw new Error(`Destination already exists and is not empty: ${destination}`);
  }

  const pointerValue = pointerValueFor(projectDir, destination);
  const pointerPath = path.join(projectDir, PROJECT_AIWG_LOCATION_FILE);

  const gitignoreUpdated = await ensureGitignorePointer(projectDir, dryRun);
  if (!dryRun) {
    await moveDirectory(source, destination);
  }
  await writePointer(projectDir, pointerValue, dryRun);

  let reindexed = false;
  let fortemiSynced = false;
  if (reindex && !dryRun) {
    await withTemporaryArtifactEnv(destination, async () => {
      await buildIndex(projectDir, { force: true, graph: 'project' });
      reindexed = true;
      if (syncFortemi) {
        syncFortemiCoreIndex(projectDir, { graph: 'project' });
        fortemiSynced = true;
      }
    });
  }

  return {
    projectDir,
    from: source,
    to: destination,
    pointerPath,
    pointerValue,
    moved: !dryRun,
    gitignoreUpdated,
    reindexed,
    fortemiSynced,
    dryRun,
  };
}
