# Build and Package Plugins
#
# Packages Claude Code plugins on tag push or manual dispatch.
# Note: npm publishing happens via GitHub Actions (requires npm provenance).

name: Build Plugins

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      clean:
        description: 'Clean plugins directory before building'
        required: false
        default: true
        type: boolean

jobs:
  build:
    name: Package Plugins
    runs-on: ubuntu-latest
    container: node:20
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Package plugins
        run: |
          if [ "${{ github.event.inputs.clean }}" = "true" ] || [ "${{ github.event_name }}" = "push" ]; then
            npm run package-plugins:clean
          else
            npm run package-plugins
          fi

      - name: Validate plugin manifests
        run: |
          echo "Validating plugin manifests..."
          for plugin in plugins/*/; do
            if [ -f "$plugin.claude-plugin/plugin.json" ]; then
              echo "✓ $(basename $plugin): manifest valid"
              cat "$plugin.claude-plugin/plugin.json" | head -5
            else
              echo "✗ $(basename $plugin): missing manifest"
              exit 1
            fi
          done

      - name: Validate marketplace.json
        run: |
          echo "Validating marketplace.json..."
          if [ -f "marketplace.json" ]; then
            echo "✓ marketplace.json exists at repo root"
            cat "marketplace.json" | head -20
          elif [ -f "plugins/.claude-plugin/marketplace.json" ]; then
            echo "✓ marketplace.json exists in plugins/"
            cat "plugins/.claude-plugin/marketplace.json" | head -20
          else
            echo "✗ marketplace.json missing"
            exit 1
          fi

      - name: Build summary
        run: |
          echo "## Plugin Build Complete"
          echo ""
          echo "### Built Plugins:"
          for plugin in plugins/*/; do
            if [ -d "$plugin" ]; then
              echo "- $(basename $plugin)"
            fi
          done
          echo ""
          echo "**Note**: npm publishing happens via GitHub Actions."

  validate:
    name: Validate Build
    runs-on: ubuntu-latest
    container: node:20
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run type check
        run: npm run typecheck

      - name: Run tests
        run: npm test -- --run
