# npm Package Publishing to Gitea and Public npm Registries
#
# Publishes the package to both Gitea's npm registry and public npmjs.org
# when a version tag is pushed. Uses CalVer versioning: vYYYY.M.PATCH
#
# REQUIRED SECRETS:
#   NPM_TOKEN    - Gitea access token with package:write scope (for Gitea registry)
#   NPMJS_TOKEN  - npmjs.org granular access token (bypasses 2FA for CI)
#
# To publish a new version:
#   1. Update version in package.json
#   2. Commit: git commit -am "release: vYYYY.M.PATCH"
#   3. Tag: git tag vYYYY.M.PATCH
#   4. Push: git push origin main --tags

name: Publish to npm registries

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run (do not publish)'
        required: false
        default: 'false'
        type: boolean
      skip_public:
        description: 'Skip publishing to public npmjs.org'
        required: false
        default: 'false'
        type: boolean

env:
  GITEA_NPM_REGISTRY: https://git.integrolabs.net/api/packages/roctinam/npm/
  NODE_VERSION: '20'

jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    container: node:20
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run type check
        run: npm run typecheck

      - name: Run tests
        run: npm test -- --run
        continue-on-error: true  # Don't fail build on test issues

      - name: Build TypeScript
        run: npm run build

      - name: Extract version info
        id: version
        run: |
          if [ "${{ github.event_name }}" = "push" ]; then
            VERSION=${GITHUB_REF#refs/tags/v}
          else
            VERSION=$(node -p "require('./package.json').version")
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Version: $VERSION"

      - name: Verify package version matches tag
        if: github.event_name == 'push'
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/v}
          PKG_VERSION=$(node -p "require('./package.json').version")
          if [ "$TAG_VERSION" != "$PKG_VERSION" ]; then
            echo "Error: Tag version ($TAG_VERSION) does not match package.json version ($PKG_VERSION)"
            exit 1
          fi
          echo "Version verified: $PKG_VERSION"

      - name: Check package contents
        run: |
          echo "=== Package contents ==="
          npm pack --dry-run 2>&1 | tee pack-output.txt
          echo ""
          echo "=== Package size ==="
          SIZE=$(grep -oE 'package size:[[:space:]]*[0-9.]+[[:space:]]*[kMG]?B' pack-output.txt || echo "unknown")
          echo "Package size: $SIZE"

      - name: Publish to Gitea npm registry
        if: ${{ github.event.inputs.dry_run != 'true' }}
        run: |
          # Configure auth for Gitea registry
          cat > .npmrc << 'NPMRC'
          //git.integrolabs.net/api/packages/roctinam/npm/:_authToken=${NODE_AUTH_TOKEN}
          NPMRC

          # Allow re-runs: treat "version already exists" as success
          npm publish --registry=${{ env.GITEA_NPM_REGISTRY }} 2>&1 | tee publish-output.txt || {
            if grep -qE "package version already exists|EPUBLISHCONFLICT|409" publish-output.txt; then
              echo "✓ Version already published to Gitea - treating as success"
            else
              echo "✗ Gitea publish failed"
              cat publish-output.txt
              exit 1
            fi
          }
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to public npmjs.org
        if: ${{ github.event.inputs.dry_run != 'true' && github.event.inputs.skip_public != 'true' }}
        run: |
          # Configure auth for public npm registry
          cat > .npmrc << 'NPMRC'
          //registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}
          NPMRC

          # Allow re-runs: treat "version already exists" as success
          npm publish --access public 2>&1 | tee publish-public-output.txt || {
            if grep -qE "cannot publish over the previously published|EPUBLISHCONFLICT|403" publish-public-output.txt; then
              echo "✓ Version already published to npmjs.org - treating as success"
            else
              echo "✗ Public npm publish failed"
              cat publish-public-output.txt
              exit 1
            fi
          }
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_TOKEN }}

      - name: Dry run - would publish
        if: ${{ github.event.inputs.dry_run == 'true' }}
        run: |
          echo "DRY RUN - Would publish version ${{ steps.version.outputs.version }}"
          echo "Registries: Gitea + npmjs.org"
          npm pack
          ls -la *.tgz

      - name: Create Gitea Release
        if: github.event_name == 'push' && github.event.inputs.dry_run != 'true'
        run: |
          VERSION=${{ steps.version.outputs.version }}

          curl -X POST \
            -H "Authorization: token ${{ secrets.NPM_TOKEN }}" \
            -H "Content-Type: application/json" \
            "${{ github.server_url }}/api/v1/repos/${{ github.repository }}/releases" \
            -d "{
              \"tag_name\": \"v${VERSION}\",
              \"name\": \"v${VERSION}\",
              \"body\": \"## Installation\\n\\n\\\`\\\`\\\`bash\\nnpm install -g aiwg@${VERSION}\\n\\\`\\\`\\\`\\n\\nAlso available from Gitea registry:\\n\\\`\\\`\\\`bash\\nnpm install -g aiwg@${VERSION} --registry=${{ env.GITEA_NPM_REGISTRY }}\\n\\\`\\\`\\\`\\n\\n## What's Changed\\n\\nSee commit history for details.\",
              \"draft\": false,
              \"prerelease\": false
            }" || echo "Release may already exist"

  verify-install:
    name: Verify Installation
    runs-on: ubuntu-latest
    container: node:20
    needs: build-and-publish
    if: ${{ github.event.inputs.dry_run != 'true' }}
    timeout-minutes: 10

    steps:
      - name: Wait for package propagation
        run: sleep 15

      - name: Verify package on Gitea registry
        run: |
          HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" \
            "${{ env.GITEA_NPM_REGISTRY }}aiwg")
          if [ "$HTTP_CODE" = "200" ]; then
            echo "✓ Package aiwg found in Gitea registry"
          else
            echo "⚠ Package not found in Gitea registry (HTTP $HTTP_CODE)"
          fi

      - name: Verify package on public npm
        if: ${{ github.event.inputs.skip_public != 'true' }}
        run: |
          # Check npmjs.org for the version
          VERSION=$(curl -s "https://registry.npmjs.org/aiwg/latest" | node -p "JSON.parse(require('fs').readFileSync('/dev/stdin','utf8')).version" 2>/dev/null || echo "unknown")
          echo "Latest version on npmjs.org: $VERSION"
          if [ "$VERSION" != "unknown" ]; then
            echo "✓ Package aiwg accessible on npmjs.org"
          else
            echo "⚠ Could not verify package on npmjs.org (may still be propagating)"
          fi
