# npm Package Publishing to Gitea and Public npm Registries
#
# Publishes the package to both Gitea's npm registry and public npmjs.org
# when a version tag is pushed. Uses CalVer versioning: vYYYY.MM.PATCH
#
# REQUIRED SECRETS:
#   GITEA_TOKEN - Gitea access token with package:write scope
#                 Generate at: Settings > Applications > Access Tokens
#   NPM_TOKEN - npmjs.org automation token
#                      Generate at: https://www.npmjs.com/settings/<user>/tokens
#
# To publish a new version:
#   1. Update version in package.json
#   2. Commit: git commit -am "release: v2024.12.0"
#   3. Tag: git tag v2024.12.0
#   4. Push: git push origin main --tags

name: Publish to npm registries

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run (do not publish)'
        required: false
        default: 'false'
        type: boolean
      publish_public:
        description: 'Also publish to public npmjs.org'
        required: false
        default: 'false'
        type: boolean

env:
  GITEA_NPM_REGISTRY: https://git.integrolabs.net/api/packages/roctinam/npm/
  NODE_VERSION: '20'

jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    container: node:20
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure npm for Gitea registry
        run: |
          # Create .npmrc with Gitea registry configuration
          cat > .npmrc << EOF
          @roctinam:registry=${{ env.GITEA_NPM_REGISTRY }}
          //git.integrolabs.net/api/packages/roctinam/npm/:_authToken=${{ secrets.GITEA_TOKEN }}
          EOF
          echo "Configured npm for Gitea registry"

      - name: Install dependencies
        run: npm ci

      - name: Run type check
        run: npm run typecheck

      - name: Run tests
        run: npm test -- --run
        continue-on-error: true  # Don't fail build on test issues

      - name: Build TypeScript
        run: npm run build

      - name: Extract version info
        id: version
        run: |
          if [ "${{ github.event_name }}" = "push" ]; then
            VERSION=${GITHUB_REF#refs/tags/v}
          else
            VERSION=$(node -p "require('./package.json').version")
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Version: $VERSION"

      - name: Verify package version matches tag
        if: github.event_name == 'push'
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/v}
          PKG_VERSION=$(node -p "require('./package.json').version")
          if [ "$TAG_VERSION" != "$PKG_VERSION" ]; then
            echo "Error: Tag version ($TAG_VERSION) does not match package.json version ($PKG_VERSION)"
            exit 1
          fi
          echo "Version verified: $PKG_VERSION"

      - name: Check package contents
        run: |
          echo "=== Package contents ==="
          npm pack --dry-run 2>&1 | tee pack-output.txt
          echo ""
          echo "=== Package size ==="
          SIZE=$(grep -oE 'package size:[[:space:]]*[0-9.]+[[:space:]]*[kMG]?B' pack-output.txt || echo "unknown")
          echo "Package size: $SIZE"

      - name: Publish to Gitea npm registry
        if: ${{ github.event.inputs.dry_run != 'true' }}
        run: |
          # Publish with scoped package name for Gitea
          npm publish --registry=${{ env.GITEA_NPM_REGISTRY }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITEA_TOKEN }}

      - name: Publish to public npm registry
        if: ${{ github.event.inputs.dry_run != 'true' && github.event.inputs.publish_public == 'true' }}
        run: |
          # Reconfigure for public npm
          cat > .npmrc << EOF
          //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}
          EOF
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Dry run - would publish
        if: ${{ github.event.inputs.dry_run == 'true' }}
        run: |
          echo "DRY RUN - Would publish version ${{ steps.version.outputs.version }}"
          echo "Registry: ${{ env.GITEA_NPM_REGISTRY }}"
          npm pack
          ls -la *.tgz

      - name: Create Gitea Release
        if: github.event_name == 'push' && github.event.inputs.dry_run != 'true'
        run: |
          # Create release via Gitea API
          VERSION=${{ steps.version.outputs.version }}

          curl -X POST \
            -H "Authorization: token ${{ secrets.GITEA_TOKEN }}" \
            -H "Content-Type: application/json" \
            "${{ github.server_url }}/api/v1/repos/${{ github.repository }}/releases" \
            -d "{
              \"tag_name\": \"v${VERSION}\",
              \"name\": \"v${VERSION}\",
              \"body\": \"## Installation\\n\\n\\\`\\\`\\\`bash\\nnpm install aiwg@${VERSION} --registry=${{ env.GITEA_NPM_REGISTRY }}\\n\\\`\\\`\\\`\\n\\n## What's Changed\\n\\nSee commit history for details.\",
              \"draft\": false,
              \"prerelease\": false
            }" || echo "Release may already exist"

  verify-install:
    name: Verify Installation
    runs-on: ubuntu-latest
    container: node:20
    needs: build-and-publish
    if: ${{ github.event.inputs.dry_run != 'true' }}
    timeout-minutes: 10

    steps:
      - name: Configure npm for Gitea registry
        run: |
          npm config set @roctinam:registry ${{ env.GITEA_NPM_REGISTRY }}

      - name: Wait for package propagation
        run: sleep 10

      - name: Install from Gitea registry
        run: |
          npm install -g aiwg --registry=${{ env.GITEA_NPM_REGISTRY }} || {
            echo "Note: Global install may fail in container, trying local"
            npm install aiwg --registry=${{ env.GITEA_NPM_REGISTRY }}
          }

      - name: Verify installation
        run: |
          npx aiwg --version || echo "Version check completed"
          npx aiwg --help | head -20 || echo "Help output completed"
