import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const addonRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const schemaPath = path.join(addonRoot, 'schemas', 'flow-graph.schema.json');
const outputPath = path.join(addonRoot, 'types', 'flow-graph.generated.ts');
const schema = JSON.parse(fs.readFileSync(schemaPath, 'utf8'));

function pascal(value) {
  return value.replace(/(^|[-_])([a-z])/g, (_match, _prefix, letter) => letter.toUpperCase());
}

function description(value, indent = '') {
  return value ? `${indent}/** ${value.replaceAll('*/', '* /')} */\n` : '';
}

function typeFor(value, depth = 0) {
  if (!value || Object.keys(value).length === 0) return 'unknown';
  if (value.$ref) return pascal(value.$ref.split('/').at(-1));
  if (Object.hasOwn(value, 'const')) return JSON.stringify(value.const);
  if (value.enum) return value.enum.map((entry) => JSON.stringify(entry)).join(' | ');
  if (value.oneOf && !value.type && !value.properties) return value.oneOf.map((entry) => typeFor(entry, depth)).join(' | ');
  if (Array.isArray(value.type)) return value.type.map((entry) => typeFor({ ...value, type: entry }, depth)).join(' | ');
  if (value.type === 'array') return `Array<${typeFor(value.items ?? {}, depth + 1)}>`;
  if (value.type === 'string') return 'string';
  if (value.type === 'number' || value.type === 'integer') return 'number';
  if (value.type === 'boolean') return 'boolean';
  if (value.type === 'null') return 'null';
  if (value.type === 'object' || value.properties || value.additionalProperties) {
    const required = new Set(value.required ?? []);
    const lines = [];
    for (const [name, property] of Object.entries(value.properties ?? {})) {
      const prefix = description(property.description, '  ');
      lines.push(`${prefix}  ${name}${required.has(name) ? '' : '?'}: ${typeFor(property, depth + 1)};`);
    }
    if (value.additionalProperties === true) lines.push('  [key: string]: unknown;');
    else if (value.additionalProperties && typeof value.additionalProperties === 'object') {
      lines.push(`  [key: string]: ${typeFor(value.additionalProperties, depth + 1)};`);
    }
    return `{\n${lines.join('\n')}\n}`;
  }
  return 'unknown';
}

function declaration(name, value) {
  const title = pascal(name);
  const docs = description(value.description);
  if (value.type === 'object' || value.properties) {
    const body = typeFor(value);
    return `${docs}export interface ${title} ${body}\n`;
  }
  return `${docs}export type ${title} = ${typeFor(value)};\n`;
}

const output = [
  '// This file is generated by scripts/generate-types.mjs from flow-graph.schema.json.',
  '// Do not edit it directly.',
  '',
  declaration('FlowGraph', schema),
  ...Object.entries(schema.definitions).map(([name, value]) => declaration(name, value)),
].join('\n');

fs.writeFileSync(outputPath, output);
console.log(`Generated ${path.relative(process.cwd(), outputPath)}`);
