name: coordinate-marketing-asset-production-from-brief-through-delivery
description: Coordinate marketing asset production from brief through delivery
model:
  name: gpt-4o
  temperature: 0.3
  max_tokens: 4000
instructions: |
  # Asset Production Command
  
  Coordinate end-to-end marketing asset production from creative brief through final delivery.
  
  ## What This Command Does
  
  1. **Initiates Production**
     - Reviews creative brief
     - Assigns resources
     - Creates production schedule
  
  2. **Manages Production**
     - Tracks progress
     - Coordinates reviews
     - Manages revisions
  
  3. **Delivers Assets**
     - Quality control
     - Asset organization
     - Delivery package
  
  ## Orchestration Flow
  
  ```
  Asset Production Request
          ↓
  [Production Coordinator] → Production Plan
          ↓
  [Traffic Manager] → Resource Assignment
          ↓
  [Creative Director] → Creative Oversight
          ↓
  [Art Director/Graphic Designer] → Design Production
          ↓
  [Video Producer] → Video Production (if applicable)
          ↓
  [Quality Controller] → QC Review
          ↓
  [Asset Manager] → Asset Organization
          ↓
  Final Asset Delivery
  ```
  
  ## Agents Involved
  
  | Agent | Role | Output |
  |-------|------|--------|
  | Production Coordinator | Lead coordination | Production plan, timeline |
  | Traffic Manager | Resources | Assignments, workload |
  | Creative Director | Oversight | Creative direction |
  | Art Director | Visual production | Design oversight |
  | Graphic Designer | Design | Digital assets |
  | Video Producer | Video | Video assets |
  | Quality Controller | QC | Quality review |
  | Asset Manager | Organization | Final delivery |
  
  ## Output Artifacts
  
  Saved to `.aiwg/marketing/production/{project-name}/`:
  
  - `production-plan.md` - Production schedule
  - `resource-allocation.md` - Team assignments
  - `progress-tracker.md` - Status tracking
  - `review-feedback/` - Review rounds
  - `delivery-manifest.md` - Asset list
  - `qc-checklist.md` - Quality checklist
  
  ## Parameter Handling
  
  ### --guidance Parameter
  
  **Purpose**: Provide upfront direction to tailor priorities and approach
  
  **Examples**:
  ```bash
  --guidance "Tight deadline, hero assets first"
  --guidance "Accessibility AAA target"
  --guidance "Localization for 5 markets"
  ```
  
  **How Applied**:
  - Parse guidance for keywords: priority, timeline, audience, focus, constraints
  - Adjust agent emphasis and output depth based on stated priorities
  - Modify deliverable order based on timeline constraints
  - Influence scope and detail level based on context
  
  ### --interactive Parameter
  
  **Purpose**: Guide through discovery questions for comprehensive input
  
  **Questions Asked** (if --interactive):
  1. What assets are being produced?
  2. What are the specifications (sizes, formats)?
  3. What is the production timeline?
  4. What brand guidelines apply?
  5. Who needs to approve final assets?
  6. Are there localization requirements?
  
  ## Usage Examples
  
  ```bash
  # Full production coordination
  /asset-production "Spring Campaign Assets"
  
  # Specific asset types
  /asset-production "Product Launch" --asset-types video
  
  # All assets
  /asset-production "Brand Refresh" --asset-types all
  
  # With strategic guidance
  /asset-production "Example" --guidance "Your specific context here"
  
  # Interactive mode
  /asset-production "Example" --interactive
  ```
  
  ## Success Criteria
  
  - [ ] Production plan approved
  - [ ] Resources assigned
  - [ ] Timeline established
  - [ ] Reviews completed
  - [ ] QC passed
  - [ ] Assets delivered
  - [ ] Documentation complete