name: conduct-comprehensive-competitive-marketing-analysis
description: Conduct comprehensive competitive marketing analysis
model:
  name: gpt-4
  temperature: 0.3
  max_tokens: 4000
instructions: |
  # Competitive Analysis Command
  
  Conduct comprehensive analysis of competitor marketing strategies, tactics, and positioning.
  
  ## What This Command Does
  
  1. **Audits Competitors**
     - Digital presence
     - Messaging and positioning
     - Content strategy
     - Campaign activity
  
  2. **Analyzes Landscape**
     - Share of voice
     - Positioning gaps
     - Best practices
  
  3. **Generates Insights**
     - Competitive advantages
     - Opportunity areas
     - Strategic recommendations
  
  ## Orchestration Flow
  
  ```
  Competitive Analysis Request
          ↓
  [Market Researcher] → Market Landscape
          ↓
  [Positioning Specialist] → Positioning Analysis
          ↓
  [Content Strategist] → Content Comparison
          ↓
  [Social Media Specialist] → Social Analysis
          ↓
  [SEO Specialist] → SEO/Digital Audit
          ↓
  [Marketing Analyst] → Benchmarks & Metrics
          ↓
  Competitive Intelligence Report
  ```
  
  ## Agents Involved
  
  | Agent | Role | Output |
  |-------|------|--------|
  | Market Researcher | Lead research | Market landscape |
  | Positioning Specialist | Positioning | Messaging analysis |
  | Content Strategist | Content | Content comparison |
  | Social Media Specialist | Social | Social audit |
  | SEO Specialist | Digital | SEO analysis |
  | Marketing Analyst | Metrics | Benchmarks |
  
  ## Output Artifacts
  
  Saved to `.aiwg/marketing/competitive/`:
  
  - `competitive-landscape.md` - Market overview
  - `competitor-profiles/` - Individual competitor analyses
  - `positioning-map.md` - Competitive positioning
  - `content-analysis.md` - Content comparison
  - `digital-audit.md` - Digital presence
  - `opportunity-gaps.md` - Strategic opportunities
  - `recommendations.md` - Action items
  
  ## Parameter Handling
  
  ### --guidance Parameter
  
  **Purpose**: Provide upfront direction to tailor priorities and approach
  
  **Examples**:
  ```bash
  --guidance "Focus on pricing and positioning gaps"
  --guidance "New market entrant analysis"
  --guidance "Feature comparison for sales enablement"
  ```
  
  **How Applied**:
  - Parse guidance for keywords: priority, timeline, audience, focus, constraints
  - Adjust agent emphasis and output depth based on stated priorities
  - Modify deliverable order based on timeline constraints
  - Influence scope and detail level based on context
  
  ### --interactive Parameter
  
  **Purpose**: Guide through discovery questions for comprehensive input
  
  **Questions Asked** (if --interactive):
  1. Which competitors should be analyzed?
  2. What aspects are most important (pricing, features, positioning)?
  3. What is the intended use of this analysis?
  4. What timeframe for data collection?
  5. Are there specific differentiators to highlight?
  
  ## Usage Examples
  
  ```bash
  # Overall competitive analysis
  /competitive-analysis
  
  # Focus on messaging
  /competitive-analysis --analysis-focus messaging
  
  # Specific competitors
  /competitive-analysis --competitors "CompA,CompB,CompC"
  
  # With strategic guidance
  /competitive-analysis "Example" --guidance "Your specific context here"
  
  # Interactive mode
  /competitive-analysis "Example" --interactive
  ```
  
  ## Success Criteria
  
  - [ ] Key competitors identified
  - [ ] Positioning mapped
  - [ ] Messaging analyzed
  - [ ] Content strategies compared
  - [ ] Digital presence audited
  - [ ] Gaps and opportunities identified
  - [ ] Actionable recommendations provided