/**
 * Gitignore Helper
 *
 * Shared module for checking and updating .gitignore files with recommended
 * AIWG runtime and provider directory patterns.
 *
 * @implements #553
 * @module src/config/gitignore
 */

import * as fs from 'fs/promises';
import * as path from 'path';
import { execFile } from 'child_process';
import { promisify } from 'util';

const execFileAsync = promisify(execFile);
const GITIGNORE_PROBE_BASENAME = '.aiwg-ignore-probe';

// ===========================
// Recommended Patterns
// ===========================

/**
 * AIWG runtime subdirectories that should be gitignored.
 * NOTE: .aiwg/ itself is intentionally NOT included — it contains
 * project artifacts (requirements, architecture, etc.) that should be versioned.
 * Only the high-churn runtime subdirectories are ignored.
 */
export const AIWG_RUNTIME_PATTERNS = [
  '.aiwg/working/',
  // .aiwg/.index/ is the artifact graph index (JSON nodes/edges + checksum
  // manifest). It is a pure build artifact, fully regenerable from corpus
  // content via `aiwg index build --all`, so it is ignored rather than committed.
  '.aiwg/.index/',
  '.aiwg/ralph/',
  '.aiwg/ralph-external/',
  '.aiwg/security-engineering/reviews/disclosures/',
];

/**
 * Provider conventional directories for non-native deployments.
 * These are generated by `aiwg use` and should not be version-controlled.
 * Claude Code native dirs (.claude/agents/, .claude/skills/, etc.) are intentionally
 * excluded from this list — they are authored artifacts worth versioning.
 */
export const PROVIDER_CONVENTIONAL_PATTERNS = [
  '.agents/',
  '.codex/',
  '.cursor/agents/',
  '.cursor/commands/',
  '.cursor/skills/',
  '.factory/skills/',
  '.factory/rules/',
  '.warp/',
  '.windsurf/agents/',
  '.windsurf/skills/',
  '.windsurf/rules/',
];

/**
 * Claude Code session state patterns (machine-local, should not be versioned).
 */
export const CLAUDE_SESSION_PATTERNS = [
  '.claude/settings.local.json',
];

/** All recommended patterns combined */
export const ALL_RECOMMENDED_PATTERNS = [
  ...AIWG_RUNTIME_PATTERNS,
  ...CLAUDE_SESSION_PATTERNS,
  ...PROVIDER_CONVENTIONAL_PATTERNS,
];

// ===========================
// Interfaces
// ===========================

export interface GitignoreCheckResult {
  exists: boolean;
  missing: string[];
  missingRuntime: string[];
  missingProvider: string[];
  missingSession: string[];
}

export interface GitignoreAppendResult {
  added: string[];
  alreadyPresent: string[];
  created: boolean;
}

// ===========================
// Core Functions
// ===========================

function isTextuallyCovered(pattern: string, lines: string[]): boolean {
  if (lines.includes(pattern)) return true;
  if (lines.includes(pattern.replace(/\/$/, ''))) return true;

  const parts = pattern.split('/').filter(Boolean);
  for (let i = 1; i < parts.length; i++) {
    const parent = parts.slice(0, i).join('/') + '/';
    if (lines.includes(parent) || lines.includes(parent.replace(/\/$/, ''))) {
      return true;
    }
  }
  return false;
}

function probePath(pattern: string): string {
  return pattern.endsWith('/') ? `${pattern}${GITIGNORE_PROBE_BASENAME}` : pattern;
}

async function isGitWorktree(projectRoot: string): Promise<boolean> {
  try {
    const { stdout } = await execFileAsync('git', ['rev-parse', '--is-inside-work-tree'], {
      cwd: projectRoot,
      windowsHide: true,
    });
    return stdout.trim() === 'true';
  } catch {
    return false;
  }
}

/**
 * Resolve effective ignore coverage through Git when possible. This honors
 * negations, .git/info/exclude, and core.excludesFile. A textual fallback keeps
 * the helper deterministic outside Git worktrees or when Git is unavailable.
 *
 * @implements #2106
 */
async function resolveCoveredPatterns(
  projectRoot: string,
  patterns: string[],
  lines: string[],
): Promise<Set<string>> {
  if (!(await isGitWorktree(projectRoot))) {
    return new Set(patterns.filter(pattern => isTextuallyCovered(pattern, lines)));
  }

  const covered = await Promise.all(patterns.map(async pattern => {
    try {
      await execFileAsync('git', ['check-ignore', '--quiet', '--', probePath(pattern)], {
        cwd: projectRoot,
        windowsHide: true,
      });
      return true;
    } catch (error) {
      const code = (error as { code?: number | string }).code;
      if (code === 1) return false;
      return isTextuallyCovered(pattern, lines);
    }
  }));

  return new Set(patterns.filter((_, index) => covered[index]));
}

/**
 * Check which recommended patterns are missing from the project's .gitignore.
 */
export async function checkGitignore(projectRoot: string): Promise<GitignoreCheckResult> {
  const gitignorePath = path.join(projectRoot, '.gitignore');

  let content = '';
  let exists = false;

  try {
    content = await fs.readFile(gitignorePath, 'utf-8');
    exists = true;
  } catch {
    // File doesn't exist — all patterns are missing
  }

  const lines = content.split('\n').map(l => l.trim());

  const covered = await resolveCoveredPatterns(projectRoot, ALL_RECOMMENDED_PATTERNS, lines);
  const missingRuntime = AIWG_RUNTIME_PATTERNS.filter(p => !covered.has(p));
  const missingSession = CLAUDE_SESSION_PATTERNS.filter(p => !covered.has(p));
  const missingProvider = PROVIDER_CONVENTIONAL_PATTERNS.filter(p => !covered.has(p));
  const missing = [...missingRuntime, ...missingSession, ...missingProvider];

  return { exists, missing, missingRuntime, missingSession, missingProvider };
}

/**
 * Append missing patterns to .gitignore, creating the file if it doesn't exist.
 * Patterns are grouped with comments.
 */
export async function appendGitignore(
  projectRoot: string,
  patterns: string[]
): Promise<GitignoreAppendResult> {
  const gitignorePath = path.join(projectRoot, '.gitignore');

  let existing = '';
  let fileExists = false;

  try {
    existing = await fs.readFile(gitignorePath, 'utf-8');
    fileExists = true;
  } catch {
    // File doesn't exist, will create
  }

  const existingLines = existing.split('\n').map(l => l.trim());
  const covered = await resolveCoveredPatterns(projectRoot, patterns, existingLines);

  const toAdd: string[] = [];
  const alreadyPresent: string[] = [];

  for (const pattern of patterns) {
    if (covered.has(pattern)) {
      alreadyPresent.push(pattern);
    } else {
      toAdd.push(pattern);
    }
  }

  if (toAdd.length > 0) {
    const runtimeToAdd = toAdd.filter(p => AIWG_RUNTIME_PATTERNS.includes(p));
    const sessionToAdd = toAdd.filter(p => CLAUDE_SESSION_PATTERNS.includes(p));
    const providerToAdd = toAdd.filter(p => PROVIDER_CONVENTIONAL_PATTERNS.includes(p));

    let block = '';

    if (runtimeToAdd.length > 0) {
      block += '\n# AIWG — ignore only high-churn runtime subdirs, NOT .aiwg/ itself\n';
      block += runtimeToAdd.join('\n') + '\n';
    }

    if (sessionToAdd.length > 0) {
      block += '\n# Claude Code local session state\n';
      block += sessionToAdd.join('\n') + '\n';
    }

    if (providerToAdd.length > 0) {
      block += '\n# Agentic provider conventional dirs (generated by aiwg use, not authored)\n';
      block += providerToAdd.join('\n') + '\n';
    }

    const newContent = existing.endsWith('\n') || existing === ''
      ? existing + block
      : existing + '\n' + block;

    await fs.writeFile(gitignorePath, newContent, 'utf-8');
  }

  return {
    added: toAdd,
    alreadyPresent,
    created: !fileExists && toAdd.length > 0,
  };
}
