# Optional Vault CI fetch spec for authenticated PostgREST and RLS qualification.
env AIWG_POSTGREST_AUTHORIZATION ${AIWG_POSTGREST_AUTHORIZATION_VAULT_PATH} ${AIWG_POSTGREST_AUTHORIZATION_VAULT_FIELD}
