name: Lint Fix Drift

on:
  push:
    paths:
      - '**/*.md'
      - 'tools/lint/**'
  pull_request:
    paths:
      - '**/*.md'
      - 'tools/lint/**'

jobs:
  fix-drift:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Check table spacing (MD058)
        run: |
          OUT=$(node tools/lint/fix-md58.mjs --target . || true)
          echo "$OUT"
          if echo "$OUT" | grep -q "would-fix"; then
            echo "MD058 drift detected. Run: node tools/lint/fix-md58.mjs --target . --write" >&2
            exit 1
          fi
      - name: Check code fences (MD031/MD040)
        run: |
          OUT=$(node tools/lint/fix-md-codefences.mjs --target . || true)
          echo "$OUT"
          if echo "$OUT" | grep -q "would-fix"; then
            echo "Code fence drift detected. Run: node tools/lint/fix-md-codefences.mjs --target . --write" >&2
            exit 1
          fi
      - name: Check headings/lists spacing (MD022/MD032)
        run: |
          OUT=$(node tools/lint/fix-md-heading-lists.mjs --target . || true)
          echo "$OUT"
          if echo "$OUT" | grep -q "would-fix"; then
            echo "Heading/list spacing drift detected. Run: node tools/lint/fix-md-heading-lists.mjs --target . --write" >&2
            exit 1
          fi
      - name: Check multiple blank lines (MD012)
        run: |
          OUT=$(node tools/lint/fix-md12.mjs --target . || true)
          echo "$OUT"
          if echo "$OUT" | grep -q "would-fix"; then
            echo "Multiple blank lines detected. Run: node tools/lint/fix-md12.mjs --target . --write" >&2
            exit 1
          fi
      - name: Check inline placeholders (MD033)
        run: |
          OUT=$(node tools/lint/fix-md33-inlineplaceholders.mjs --target . || true)
          echo "$OUT"
          if echo "$OUT" | grep -q "would-fix"; then
            echo "Inline placeholders detected. Run: node tools/lint/fix-md33-inlineplaceholders.mjs --target . --write" >&2
            exit 1
          fi
      - name: Check list indentation (MD005/MD007)
        run: |
          OUT=$(node tools/lint/fix-md5-7-lists.mjs --target . || true)
          echo "$OUT"
          if echo "$OUT" | grep -q "would-fix"; then
            echo "List indentation drift detected. Run: node tools/lint/fix-md5-7-lists.mjs --target . --write" >&2
            exit 1
          fi
      - name: Check heading punctuation (MD026)
        run: |
          OUT=$(node tools/lint/fix-md26-headpunct.mjs --target . || true)
          echo "$OUT"
          if echo "$OUT" | grep -q "would-fix"; then
            echo "Heading punctuation drift detected. Run: node tools/lint/fix-md26-headpunct.mjs --target . --write" >&2
            exit 1
          fi
      - name: Check first-line H1 (MD041)
        run: |
          OUT=$(node tools/lint/fix-md41-firsth1.mjs --target . || true)
          echo "$OUT"
          if echo "$OUT" | grep -q "would-fix"; then
            echo "First-line H1 drift detected. Run: node tools/lint/fix-md41-firsth1.mjs --target . --write" >&2
            exit 1
          fi
      - name: Check final newline (MD047)
        run: |
          OUT=$(node tools/lint/fix-md47-finalnewline.mjs --target . || true)
          echo "$OUT"
          if echo "$OUT" | grep -q "would-fix"; then
            echo "Final newline drift detected. Run: node tools/lint/fix-md47-finalnewline.mjs --target . --write" >&2
            exit 1
          fi
      - name: Check code span spacing (MD038)
        run: |
          OUT=$(node tools/lint/fix-md38-codespace.mjs --target . || true)
          echo "$OUT"
          if echo "$OUT" | grep -q "would-fix"; then
            echo "Code span spacing drift detected. Run: node tools/lint/fix-md38-codespace.mjs --target . --write" >&2
            exit 1
          fi
